#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHUbDaUR/AYQE3NziN3KYg/xIyXEQAYdHt+jh545WkUo ubuntu@ubuntu
package_update: true
package_upgrade: true
packages:
  - nginx
  - docker
  - docker compose

runcmd:
  - mkdir -p /var/www/html
  - cp -r /app/src/ /var/www/html
  - systemctl restart nginx
